on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
          FTP_SERVER:  ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.SFTP_USER }}
          FTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          METHOD: sftp
          REMOTE_DIR: /home/papa31/
          PORT: 22


